config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :location, only: [:index] do
    member do
     post :add
     post :share
     get  :get_form
     delete :remove
     delete :remove_shared
     delete :remove_shared_with_me
    end
  end
  get 'my_locations/:id', to: 'users#my_locations', as: 'my_locations'
  get 'shared_locations/:id', to: 'users#shared_locations', as: 'shared_locations'
  get 'shared_locations_with_me/:id', to: 'users#shared_locations_with_me', as: 'shared_locations_with_me'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shared_location.rb
class SharedLocation < ApplicationRecord
  belongs_to :user
  belongs_to :shared_with, class_name: "User"
  belongs_to :user_location
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_locations
  has_many :shared_locations, foreign_key: 'user_id', class_name: 'SharedLocation', dependent: :destroy
  has_many :shared_with_locations, foreign_key: 'shared_with_id', class_name: 'SharedLocation', dependent: :destroy
end

app/models/user_location.rb
class UserLocation < ApplicationRecord
  belongs_to :user
  has_many :shared_locations
  geocoded_by :address
  after_validation :geocode, if: :address_changed?
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user_locations = current_user.user_locations
    @shared_location = SharedLocation.first
  end
end

app/controllers/location_controller.rb
class LocationController < ApplicationController
  def add
    current_user.user_locations.create(address: params[:user][:address])
    @user_locations = current_user.user_locations
  end

  def share
    current_user.shared_locations.create(shared_with: User.find(params[:user][:user_id]),  user_location: UserLocation.find(params[:user][:user_locations_id]))
  end

  def get_form
    @user = User.find(params[:id])
    render partial: 'get_form', locals: { user: @user, user_location_id: params[:user_location_id] }
  end

  def remove
    UserLocation.find(params[:id]).destroy
  end

  def remove_shared
    SharedLocation.find(params[:id]).destroy
  end

  def remove_shared_with_me
    SharedLocation.find(params[:id]).destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def my_locations
    @user_locations = current_user.user_locations
  end

  def shared_locations
    @user_locations = SharedLocation.joins('left join users on shared_locations.shared_with_id = users.id')
                          .joins('left join user_locations on user_locations.id = shared_locations.user_location_id')
                          .select('shared_locations.id, user_locations.latitude, user_locations.longitude, user_locations.address, users.email')
                          .where('shared_locations.user_id = ?', current_user.id)
  end

  def shared_locations_with_me
    @user_locations = SharedLocation.joins('left join users on shared_locations.user_id = users.id')
                          .joins('left join user_locations on user_locations.id = shared_locations.user_location_id')
                          .select('shared_locations.id, user_locations.latitude, user_locations.longitude, user_locations.address, users.email')
                          .where('shared_locations.shared_with_id = ?', current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/location_helper.rb
module LocationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/share_location_helper.rb
module ShareLocationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/_my_locations.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longituide</th>
    <th>share</th>
    <th>Delete</th>
    <th>Location</th>
  </tr>
  </thead>
  <tbody>
  <% user_locations.each do |location| %>
      <tr id="<%= location.id %>">
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td>
          <%= link_to "Share", 'share_with', "data-toggle" => "modal", 'data-target' => '#shareModal', class: 'btn btn-outline-success', onclick: "share_location(#{location.id})" %>
        </td>
        <td>
          <%= link_to "Delete", remove_location_path(location.id), class: 'btn btn-outline-success', method: :delete, remote: true, data: {confirm: 'Are you sure want to delete ?'} %>
        </td>
        <td>
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{ location.latitude}%2C#{location.longitude}&key=AIzaSyCtCLPF6KYDTfKXpHVvYXsOeoQOXq9AnJM" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/_shared_locations.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Shared with</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longituide</th>
    <th>Delete</th>
    <th>Location</th>
  </tr>
  </thead>
  <tbody>
  <% user_locations.each do |location| %>
      <tr id="<%= location.id %>">
        <td><%= location.email %></td>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td>
          <%= link_to "Delete", remove_shared_location_path(location.id), class: 'btn btn-outline-success', method: :delete, remote: true, data: {confirm: 'Are you sure want to delete ?'} %>
        </td>
        <td>
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{ location.latitude}%2C#{location.longitude}&key=AIzaSyCtCLPF6KYDTfKXpHVvYXsOeoQOXq9AnJM" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/_shared_locations_with_me.html.erb
<table class="table table-bordered">
  <thead>
  <tr>
    <th>Shared By</th>
    <th>Address</th>
    <th>Latitude</th>
    <th>Longituide</th>
    <th>Delete</th>
    <th>location</th>
  </tr>
  </thead>
  <tbody>
  <% user_locations.each do |location| %>
      <tr id="<%= location.id %>">
        <td><%= location.email %></td>
        <td><%= location.address %></td>
        <td><%= location.latitude %></td>
        <td><%= location.longitude %></td>
        <td>
          <%= link_to "Delete", remove_shared_with_me_location_path(location.id), class: 'btn btn-outline-success', method: :delete, remote: true, data: {confirm: 'Are you sure want to delete ?'} %>
        </td>
        <td>
          <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{ location.latitude}%2C#{location.longitude}&key=AIzaSyCtCLPF6KYDTfKXpHVvYXsOeoQOXq9AnJM" %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<h1 class="h1 d-inline">Locations</h1> --
<%= link_to "Add Location", '', :id => 'login', "data-toggle" => "modal", 'data-target' => '#share_location', class: 'btn btn-outline-success' %>
<div class="row mt-4 mb-4">
  <div class="col-md-4">
    <%= link_to "My Locations", my_locations_path(current_user.id), remote: true, class: 'btn btn-outline-success' %>
  </div>
  <div class="col-md-4">
    <%= link_to "Shared Locations", shared_locations_path(current_user.id), remote: true, class: 'btn btn-outline-success' %>
  </div>
  <div class="col-md-4">
    <%= link_to "Shared Locations with me", shared_locations_with_me_path(current_user.id), remote: true, class: 'btn btn-outline-success' %>
  </div>
</div>
<!-- Modal -->
<div class="modal fade" id="share_location" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Location address(keep it simple as it is a free tier google
          ip)</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_with model: current_user, url: add_location_path(current_user.id), method: :post do |f| %>
            <div class="row">
              <div class="col-md-2">
                <label class="label">Location</label>
              </div>
              <div class="col-md-4">
                <%= f.text_field :address %>
              </div>
              <div class="row-md-2">
                <%= f.submit %>
              </div>
            </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close_share_location">Close</button>
      </div>
    </div>
  </div>
</div>
<div class="row" id="user_locations">
  <div class="col-md-8" id="my_locations">
    <%= render partial: 'my_locations', locals: {user_locations: @user_locations} %>
  </div>
</div>
<div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Share location with users:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="share_form">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal" id="close_shareModal">Close</button>
      </div>
    </div>
  </div>
</div>
<script>
    function share_location(user_location_id) {
        $.ajax({
            url: "<%= get_form_location_path(current_user.id) %>",
            method: 'get',
            data: 'user_location_id=' + encodeURIComponent(user_location_id),
            success: function (data) {
                $('#share_form').html(data);
            }
        });
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sloc</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark  mb-2">
  <div class="container">
    <a class="navbar-brand text-capitalize" href="/">Share loc</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
           <%= link_to "welcome - #{current_user.email}", '', class: 'nav-link' if user_signed_in? %>
        </li>
        <li class="nav-item dropdown">
          <ul class="list-unstyled">
            <% if user_signed_in? %>
                <li class="list-item">
                  <%= link_to('Logout', destroy_user_session_path, class: 'nav-link', method: :delete) %>
                </li>
            <% else %>
                <li class="list-item">
                  <%= link_to('Login', new_user_session_path, class: 'nav-link') %>
                </li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
  <% if flash[:notice] %>
      <p class="alert"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
  <% end %>
  <%= yield %>
</div>
<div class="fixed-bottom bg-dark text-light text-center"><span class="text-capitalize">All rights reserved</span></div>
</body>
</html>

app/views/location/_get_form.html.erb
<%= form_with model: current_user, url: share_location_path(current_user.id), method: :post do |f| %>
    <div class="row">
      <div class="col-md-8">
        <%= f.select :user_id, options_from_collection_for_select(User.all, :id, :email) %>
        <%= f.hidden_field :user_locations_id , value: user_location_id %>
      </div>
      <div class="col-md-2">
        <%= f.submit %>
      </div>
    </div>
<% end %>

app/views/location/add.js.erb
$('#close_share_location').click();
$('#my_locations').html("<%= j render partial: 'home/my_locations', locals: {user_locations: @user_locations}  %>");

app/views/location/remove.js.erb
$("#<%= params[:id] %>").remove();

app/views/location/remove_shared.js.erb
$("#<%= params[:id] %>").remove();

app/views/location/remove_shared_with_me.js.erb
$("#<%= params[:id] %>").remove();

app/views/location/share.js.erb
$('#close_shareModal').click();

app/views/users/my_locations.js.erb
$('#my_locations').html("<%= j render partial: 'home/my_locations', locals: {user_locations: @user_locations}  %>");

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/shared_locations.js.erb
$('#my_locations').html("<%= j render partial: 'home/shared_locations', locals: {user_locations: @user_locations}  %>");

app/views/users/shared_locations_with_me.js.erb
$('#my_locations').html("<%= j render partial: 'home/shared_locations_with_me', locals: {user_locations: @user_locations}  %>");